[package]
name = "bitcoin_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }

[[bin]]
name = "bitcoin_runner"
path = "src/main.rs"